// Username management utilities

const USERNAME_STORAGE_KEY = 'wikiGo-username'
const USERNAME_AUTO_GENERATED_KEY = 'wikiGo-username-auto-generated'

/**
 * Generate a random username
 * Format: Player_XXXXXX (where X is alphanumeric)
 */
export function generateRandomUsername() {
  const adjectives = ['Swift', 'Clever', 'Bold', 'Quick', 'Wise', 'Sharp', 'Bright', 'Smart', 'Fast', 'Brave'];
  const nouns = ['Explorer', 'Navigator', 'Seeker', 'Traveler', 'Pioneer', 'Voyager', 'Wanderer', 'Adventurer', 'Scout', 'Pathfinder'];
  
  const randomAdjective = adjectives[Math.floor(Math.random() * adjectives.length)];
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
  const randomNum = Math.floor(Math.random() * 10000);
  
  return `${randomAdjective}${randomNoun}${randomNum}`;
}

/**
 * Get stored username from localStorage
 */
export function getStoredUsername() {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem(USERNAME_STORAGE_KEY);
}

/**
 * Set username in localStorage
 */
export function setStoredUsername(username, isAutoGenerated = false) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(USERNAME_STORAGE_KEY, username);
  localStorage.setItem(USERNAME_AUTO_GENERATED_KEY, isAutoGenerated ? 'true' : 'false');
}

/**
 * Check if username was auto-generated
 */
export function isUsernameAutoGenerated() {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem(USERNAME_AUTO_GENERATED_KEY) === 'true';
}

/**
 * Get existing username or generate and store a new one
 */
export function getOrCreateUsername() {
  let username = getStoredUsername();
  if (!username) {
    username = generateRandomUsername();
    setStoredUsername(username, true); // Mark as auto-generated
  }
  return username;
}

/**
 * Check if user has submitted score today
 */
export function hasSubmittedToday(dateString) {
  if (typeof window === 'undefined') return false;
  const key = `wikiGo-submitted-${dateString}`;
  return localStorage.getItem(key) === 'true';
}

/**
 * Mark that user has submitted score today
 */
export function markSubmittedToday(dateString) {
  if (typeof window === 'undefined') return;
  const key = `wikiGo-submitted-${dateString}`;
  localStorage.setItem(key, 'true');
}

