// Username management utilities

import { uniqueNamesGenerator, adjectives, colors, animals } from 'unique-names-generator';

const USERNAME_STORAGE_KEY = 'wikiGo-username'
const USERNAME_AUTO_GENERATED_KEY = 'wikiGo-username-auto-generated'

/**
 * Generate a random username using unique-names-generator
 * Format: {Adjective}{Color}{Animal} or {Adjective}{Animal}
 * Example: SwiftBlueTiger, BraveEagle, CleverWolf
 * Uses the library's built-in dictionaries for maximum variety
 */
export function generateRandomUsername() {
  // Generate a unique name using the library's built-in dictionaries
  // This gives us access to hundreds of words, not just 30*20 combinations
  const name = uniqueNamesGenerator({
    dictionaries: [adjectives, colors, animals],
    separator: '', // No separator for username format
    length: 3, // Use 3 words (adjective + color + animal) for more variety
    style: 'capital', // Capitalize each word
  });
  
  return name;
}

/**
 * Get stored username from localStorage
 */
export function getStoredUsername() {
  if (typeof window === 'undefined') return null;
  return localStorage.getItem(USERNAME_STORAGE_KEY);
}

/**
 * Set username in localStorage
 */
export function setStoredUsername(username, isAutoGenerated = false) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(USERNAME_STORAGE_KEY, username);
  localStorage.setItem(USERNAME_AUTO_GENERATED_KEY, isAutoGenerated ? 'true' : 'false');
}

/**
 * Check if username was auto-generated
 */
export function isUsernameAutoGenerated() {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem(USERNAME_AUTO_GENERATED_KEY) === 'true';
}

/**
 * Get existing username or generate and store a new one
 */
export function getOrCreateUsername() {
  let username = getStoredUsername();
  if (!username) {
    username = generateRandomUsername();
    setStoredUsername(username, true); // Mark as auto-generated
  }
  return username;
}

/**
 * Check if user has submitted score today
 */
export function hasSubmittedToday(dateString) {
  if (typeof window === 'undefined') return false;
  const key = `wikiGo-submitted-${dateString}`;
  return localStorage.getItem(key) === 'true';
}

/**
 * Mark that user has submitted score today
 */
export function markSubmittedToday(dateString) {
  if (typeof window === 'undefined') return;
  const key = `wikiGo-submitted-${dateString}`;
  localStorage.setItem(key, 'true');
}

